<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.16">
  <POU Name="FB_HeavyWash" Id="{9f802e7e-d184-4f69-9a2e-1ffb9c72b5ed}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION_BLOCK FB_HeavyWash IMPLEMENTS I_WashStrategy
VAR_INPUT
END_VAR
VAR_OUTPUT
END_VAR
VAR
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[]]></ST>
    </Implementation>
    <Method Name="GetDuration" Id="{ec67eb37-0347-4b70-b83b-68d9b1c95420}">
      <Declaration><![CDATA[{warning 'add method implementation '}
METHOD GetDuration
]]></Declaration>
      <Implementation>
        <ST><![CDATA[]]></ST>
      </Implementation>
    </Method>
    <Method Name="Start" Id="{d4cee526-49d0-47d8-b600-0e4eac7a0ef5}">
      <Declaration><![CDATA[{warning 'add method implementation '}
METHOD Start
]]></Declaration>
      <Implementation>
        <ST><![CDATA[]]></ST>
      </Implementation>
    </Method>
    <Method Name="Stop" Id="{f4f576a4-6ca0-402e-9698-3f2459d6a217}">
      <Declaration><![CDATA[{warning 'add method implementation '}
METHOD Stop
]]></Declaration>
      <Implementation>
        <ST><![CDATA[]]></ST>
      </Implementation>
    </Method>
    <LineIds Name="FB_HeavyWash">
      <LineId Id="9" Count="0" />
    </LineIds>
    <LineIds Name="FB_HeavyWash.GetDuration">
      <LineId Id="4" Count="0" />
    </LineIds>
    <LineIds Name="FB_HeavyWash.Start">
      <LineId Id="4" Count="0" />
    </LineIds>
    <LineIds Name="FB_HeavyWash.Stop">
      <LineId Id="4" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>