<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.16">
  <POU Name="FB_NormalWash" Id="{3a7130f4-98e7-4e05-a785-86970010f516}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION_BLOCK FB_NormalWash IMPLEMENTS I_WashStrategy
VAR_INPUT
END_VAR
VAR_OUTPUT
END_VAR
VAR
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[]]></ST>
    </Implementation>
    <Method Name="GetDuration" Id="{8a29e230-838d-43a3-91a5-5fe3abf18f33}">
      <Declaration><![CDATA[{warning 'add method implementation '}
METHOD GetDuration : TIME
]]></Declaration>
      <Implementation>
        <ST><![CDATA[]]></ST>
      </Implementation>
    </Method>
    <Method Name="GetRinseCount" Id="{ed14ee3b-bdb8-4ff8-9ba6-d9ceaff581ab}">
      <Declaration><![CDATA[METHOD GetRinseCount : INT
VAR_INPUT
END_VAR
]]></Declaration>
      <Implementation>
        <ST><![CDATA[]]></ST>
      </Implementation>
    </Method>
    <Method Name="StartSpin" Id="{d4159490-279d-4bb9-9bc6-a33a50e094da}">
      <Declaration><![CDATA[METHOD StartSpin : BOOL
VAR_INPUT
END_VAR
]]></Declaration>
      <Implementation>
        <ST><![CDATA[]]></ST>
      </Implementation>
    </Method>
    <Method Name="StartWash" Id="{5d96b91b-8f5c-464e-8848-f2528787bc71}">
      <Declaration><![CDATA[{warning 'add method implementation '}
METHOD StartWash : BOOL
VAR_INPUT
	iMotor : I_Motor;
END_VAR
]]></Declaration>
      <Implementation>
        <ST><![CDATA[]]></ST>
      </Implementation>
    </Method>
    <Method Name="Stop" Id="{6de0414a-4a56-4f90-9038-d4f00b94516c}">
      <Declaration><![CDATA[{warning 'add method implementation '}
METHOD Stop
]]></Declaration>
      <Implementation>
        <ST><![CDATA[]]></ST>
      </Implementation>
    </Method>
    <LineIds Name="FB_NormalWash">
      <LineId Id="9" Count="0" />
    </LineIds>
    <LineIds Name="FB_NormalWash.GetDuration">
      <LineId Id="4" Count="0" />
    </LineIds>
    <LineIds Name="FB_NormalWash.GetRinseCount">
      <LineId Id="5" Count="0" />
    </LineIds>
    <LineIds Name="FB_NormalWash.StartSpin">
      <LineId Id="5" Count="0" />
    </LineIds>
    <LineIds Name="FB_NormalWash.StartWash">
      <LineId Id="4" Count="0" />
    </LineIds>
    <LineIds Name="FB_NormalWash.Stop">
      <LineId Id="4" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>