<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.16">
  <POU Name="FB_BiDirectionConveyer" Id="{9bbb15e2-4ac3-4493-ba62-1b0aee54c0f3}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION_BLOCK FB_BiDirectionConveyer
VAR_INPUT
END_VAR
VAR_OUTPUT
END_VAR
VAR
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[]]></ST>
    </Implementation>
    <LineIds Name="FB_BiDirectionConveyer">
      <LineId Id="9" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>