<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.16">
  <POU Name="FB_Crane" Id="{b92e7889-f852-4a96-a33c-3002a177f6c5}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION_BLOCK FB_Crane
VAR_INPUT
END_VAR
VAR_OUTPUT
END_VAR
VAR
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[]]></ST>
    </Implementation>
    <LineIds Name="FB_Crane">
      <LineId Id="9" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>