<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.16">
  <POU Name="FB_RAT" Id="{a53e8369-ccc0-4a67-aaae-0302ede3efed}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION_BLOCK FB_RAT
VAR_INPUT
END_VAR
VAR_OUTPUT
END_VAR
VAR
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[]]></ST>
    </Implementation>
    <LineIds Name="FB_RAT">
      <LineId Id="9" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>