<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.16">
  <POU Name="FB_Car" Id="{64f4a3f7-7bc8-4255-8be5-c373cd978fbd}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION_BLOCK FB_Car EXTENDS FB_Vehicle


VAR_IN_OUT
	
END_VAR
VAR
	fbEngine : FB_PetrolEngine;
	sCarName : STRING(300);
	fTotalDistanceTravelled : REAL;
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[
]]></ST>
    </Implementation>
    <Method Name="VehicleName" Id="{0c1aa78b-d601-4558-9aaa-d25b1e3c08b6}">
      <Declaration><![CDATA[METHOD VehicleName : STRING
VAR_INPUT
	sName : STRING;
END_VAR
]]></Declaration>
      <Implementation>
        <ST><![CDATA[sVehicleName := CONCAT('Car name is ', sName);]]></ST>
      </Implementation>
    </Method>
    <LineIds Name="FB_Car">
      <LineId Id="23" Count="0" />
      <LineId Id="15" Count="0" />
    </LineIds>
    <LineIds Name="FB_Car.VehicleName">
      <LineId Id="5" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>