<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.16">
  <POU Name="Fb_Truck" Id="{9292bc31-f0a9-40d0-badc-f9fec3c645f1}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION_BLOCK Fb_Truck EXTENDS FB_Vehicle

VAR_INPUT
	
END_VAR
VAR
	
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[]]></ST>
    </Implementation>
    <Method Name="VehicleName" Id="{764ae11f-73c9-45b4-94ab-4cad57498ec1}">
      <Declaration><![CDATA[METHOD VehicleName : STRING
VAR_INPUT
	sName : STRING;
END_VAR
VAR
	sVehicleName : STRING;
END_VAR
]]></Declaration>
      <Implementation>
        <ST><![CDATA[THIS^.sVehicleName := CONCAT('Truck name is ', sName);]]></ST>
      </Implementation>
    </Method>
    <LineIds Name="Fb_Truck">
      <LineId Id="9" Count="0" />
    </LineIds>
    <LineIds Name="Fb_Truck.VehicleName">
      <LineId Id="6" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>