<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.16">
  <POU Name="MAIN" Id="{1eb1897d-6236-408c-b038-5d9babf5f616}" SpecialFunc="None">
    <Declaration><![CDATA[PROGRAM MAIN
VAR
	fbCar : FB_Car;
	fbVehicle :REFERENCE TO FB_Vehicle;
	fbTruck : FB_Truck;

	bStart : BOOL;
	bStop : BOOL;
	sName : STRING(300);
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[fbVehicle REF= fbCar;
fbVehicle.VehicleName('TATA');
]]></ST>
    </Implementation>
    <LineIds Name="MAIN">
      <LineId Id="63" Count="0" />
      <LineId Id="60" Count="0" />
      <LineId Id="62" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>