<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.16">
  <POU Name="FB_AisleController" Id="{771eb6a0-9aa8-4ab2-8843-b7501fe717eb}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION_BLOCK FB_AisleController
VAR_INPUT
END_VAR
VAR_OUTPUT
END_VAR
VAR
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[]]></ST>
    </Implementation>
    <LineIds Name="FB_AisleController">
      <LineId Id="9" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>