<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.16">
  <POU Name="FB_InFeedController" Id="{ff4e95ef-2fe1-4fc4-a99c-7d6bb92f39bb}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION_BLOCK FB_InFeedController
VAR_INPUT
END_VAR
VAR_OUTPUT
END_VAR
VAR
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[]]></ST>
    </Implementation>
    <LineIds Name="FB_InFeedController">
      <LineId Id="9" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>