<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.16">
  <POU Name="FB_LoopController" Id="{f48adaf0-df81-44d4-869d-09b0da41d4aa}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION_BLOCK FB_LoopController
VAR_INPUT
END_VAR
VAR_OUTPUT
END_VAR
VAR
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[]]></ST>
    </Implementation>
    <LineIds Name="FB_LoopController">
      <LineId Id="9" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>