<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.16">
  <POU Name="FB_OutFeedController" Id="{92429ae1-de73-4d9b-b929-da1182fa1b53}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION_BLOCK FB_OutFeedController
VAR_INPUT
END_VAR
VAR_OUTPUT
END_VAR
VAR
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[]]></ST>
    </Implementation>
    <LineIds Name="FB_OutFeedController">
      <LineId Id="9" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>