<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.16">
  <POU Name="FB_Light" Id="{f889c253-9541-476c-bf4c-9f64afbed404}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION_BLOCK FB_Light IMPLEMENTS __System.IQueryInterface
VAR_INPUT
END_VAR
VAR_OUTPUT
END_VAR
VAR
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[]]></ST>
    </Implementation>
    <LineIds Name="FB_Light">
      <LineId Id="9" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>