<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.16">
  <POU Name="MAIN" Id="{d8671499-345b-4312-95fc-c382a6413344}" SpecialFunc="None">
    <Declaration><![CDATA[PROGRAM MAIN
VAR
	fbMotor1 : InductionMotor;
	fMotorRunningStatus : BOOL;
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[

fMotorRunningStatus := fbMotor1.Start();
]]></ST>
    </Implementation>
    <LineIds Name="MAIN">
      <LineId Id="7" Count="0" />
      <LineId Id="2" Count="0" />
      <LineId Id="9" Count="1" />
    </LineIds>
  </POU>
</TcPlcObject>