<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.16">
  <POU Name="MotorController" Id="{ef45ef2d-b6ed-4d33-bf44-a2461ae43f9a}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION MotorController : BOOl
VAR_INPUT
	iMotor1 : I_Motor;
	bRun : BOOL;
	fSpeed : REAL;
END_VAR
VAR
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[
IF bRun THEN
	iMotor1.Start();
ELSE
	iMotor1.Stop();
END_IF
]]></ST>
    </Implementation>
    <LineIds Name="MotorController">
      <LineId Id="9" Count="0" />
      <LineId Id="7" Count="0" />
      <LineId Id="13" Count="0" />
      <LineId Id="17" Count="0" />
      <LineId Id="19" Count="0" />
      <LineId Id="14" Count="0" />
      <LineId Id="16" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>