<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.16">
  <POU Name="MAIN" Id="{31fe5ed8-789a-43d7-9bb7-c38f88336644}" SpecialFunc="None">
    <Declaration><![CDATA[PROGRAM MAIN
VAR
	fbBottle : FB_BottleFiller;
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[fbBottle.StartFilling();]]></ST>
    </Implementation>
    <LineIds Name="MAIN">
      <LineId Id="2" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>