<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.16">
  <POU Name="MAIN" Id="{290377bf-b4e5-4a72-86a7-d35d66667e63}" SpecialFunc="None">
    <Declaration><![CDATA[PROGRAM MAIN
VAR
	 fbAlarm : FB_AlarmController;
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[fbAlarm();]]></ST>
    </Implementation>
    <LineIds Name="MAIN">
      <LineId Id="2" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>