<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.16">
  <POU Name="FB_Drill" Id="{0fab13f1-c360-4135-8aab-1eb9236f9c07}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION_BLOCK FB_Drill
VAR_INPUT
	bStart : BOOL;
END_VAR
VAR_OUTPUT
END_VAR
VAR
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[]]></ST>
    </Implementation>
    <Transition Name="TRANS_Check" Id="{3e98b030-fb01-478e-be50-7cbc290f2709}">
      <Implementation>
        <ST><![CDATA[bStart := TRUE;
TRANS_Check := bStart;]]></ST>
      </Implementation>
    </Transition>
    <LineIds Name="FB_Drill">
      <LineId Id="9" Count="0" />
    </LineIds>
    <LineIds Name="FB_Drill.TRANS_Check">
      <LineId Id="2" Count="0" />
      <LineId Id="1" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>