<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.16">
  <POU Name="UpdateTimeStampWithSystemTime" Id="{be573526-e4b8-4b40-bc83-dbbbda21196c}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION UpdateTimeStampWithSystemTime : BOOL
VAR_INPUT
	stEvent : REFERENCE TO ST_Event;
END_VAR
VAR
	fbGetSystemTime  : GETSYSTEMTIME;
	stFileTime : T_FILETIME;
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[fbGetSystemTime(timeLoDW => stFiletime.dwLowDateTime,
				 timeHiDW => stFileTime.dwHighDateTime);
stEvent.dtTimeStamp := FILETIME_TO_DT(fileTime := stFileTime);]]></ST>
    </Implementation>
    <LineIds Name="UpdateTimeStampWithSystemTime">
      <LineId Id="7" Count="0" />
      <LineId Id="11" Count="1" />
    </LineIds>
  </POU>
</TcPlcObject>