<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.16">
  <POU Name="PRG_TEST" Id="{8d592696-06f7-48f3-8336-fe042a95e832}" SpecialFunc="None">
    <Declaration><![CDATA[PROGRAM PRG_TEST
VAR
	
fbBottleFiller_Test : FB_BottleFiller_Test;
fbBottle : FB_BottleFiller;
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[TcUnit.RUN();]]></ST>
    </Implementation>
    <LineIds Name="PRG_TEST">
      <LineId Id="2" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>