<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.16">
  <POU Name="MAIN" Id="{8da3d096-1754-40ee-b80d-caff5cf9410f}" SpecialFunc="None">
    <Declaration><![CDATA[PROGRAM MAIN
VAR
	fbConveyer : FB_Conveyer;
	fbMachineController : FB_MachineController(_iConveyer := fbConveyer);
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[
fbMachineController();
]]></ST>
    </Implementation>
    <LineIds Name="MAIN">
      <LineId Id="7" Count="1" />
      <LineId Id="2" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>