<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.16">
  <POU Name="MAIN" Id="{6f8a7c5c-65cf-49f7-b333-8561dc956ed3}" SpecialFunc="None">
    <Declaration><![CDATA[PROGRAM MAIN
VAR
	fbRead : FB_ModBusReadExample;
	fbWrite : FB_ModBusWriteExample;
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[fbRead();
fbWrite();]]></ST>
    </Implementation>
    <LineIds Name="MAIN">
      <LineId Id="2" Count="0" />
      <LineId Id="8" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>