<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.16">
  <POU Name="FB_Car" Id="{7204386d-eef9-428d-9a12-9c863ebad0ab}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION_BLOCK ABSTRACT FB_Car IMPLEMENTS I_Vehicle
VAR_INPUT
END_VAR
VAR_OUTPUT
END_VAR
VAR
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[]]></ST>
    </Implementation>
    <Method Name="Drive" Id="{2860be81-2485-4d18-a770-042a307e571d}">
      <Declaration><![CDATA[METHOD Drive : BOOL
VAR_INPUT
END_VAR
]]></Declaration>
      <Implementation>
        <ST><![CDATA[]]></ST>
      </Implementation>
    </Method>
    <Method Name="Running" Id="{a9c4540a-b3c4-4ff9-a5b7-95c3ea3c4cf5}">
      <Declaration><![CDATA[METHOD Running : BOOL
VAR_INPUT
END_VAR
]]></Declaration>
      <Implementation>
        <ST><![CDATA[]]></ST>
      </Implementation>
    </Method>
    <Method Name="Start" Id="{a27c00aa-7d49-4168-a041-860d21db2d4c}">
      <Declaration><![CDATA[METHOD ABSTRACT Start : BOOL
VAR_INPUT
END_VAR
]]></Declaration>
      <Implementation>
        <ST><![CDATA[]]></ST>
      </Implementation>
    </Method>
    <LineIds Name="FB_Car">
      <LineId Id="9" Count="0" />
    </LineIds>
    <LineIds Name="FB_Car.Drive">
      <LineId Id="5" Count="0" />
    </LineIds>
    <LineIds Name="FB_Car.Running">
      <LineId Id="5" Count="0" />
    </LineIds>
    <LineIds Name="FB_Car.Start">
      <LineId Id="5" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>