<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.16">
  <POU Name="FB_Motor" Id="{a23ca182-15e8-4e99-91c3-848ac3b0a8af}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION_BLOCK FB_Motor

VAR_STAT
	nNum : INT;
END_VAR
VAR
	{attribute 'hide'}
	bStart : BOOL := TRUE;
END_VAR]]></Declaration>
    <Implementation>
      <ST><![CDATA[]]></ST>
    </Implementation>
    <Method Name="Start" Id="{69721c44-875e-461f-8521-a56654156274}">
      <Declaration><![CDATA[METHOD Start : BOOL
VAR_INPUT
END_VAR


]]></Declaration>
      <Implementation>
        <ST><![CDATA[nNum := nNum + 1;]]></ST>
      </Implementation>
    </Method>
    <LineIds Name="FB_Motor">
      <LineId Id="9" Count="0" />
    </LineIds>
    <LineIds Name="FB_Motor.Start">
      <LineId Id="5" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>