<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.16">
  <POU Name="FB_TataNexon" Id="{899ab903-5695-4ffe-b13d-79245160d5f3}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION_BLOCK FB_TataNexon EXTENDS FB_Car

VAR
	bStart : BOOL;
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[]]></ST>
    </Implementation>
    <Method Name="Start" Id="{e8e18b09-07b4-493b-8fdd-1ae28fb607d3}">
      <Declaration><![CDATA[METHOD  Start : BOOL
VAR_INPUT
END_VAR
]]></Declaration>
      <Implementation>
        <ST><![CDATA[bStart := TRUE;]]></ST>
      </Implementation>
    </Method>
    <LineIds Name="FB_TataNexon">
      <LineId Id="9" Count="0" />
    </LineIds>
    <LineIds Name="FB_TataNexon.Start">
      <LineId Id="5" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>