<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.16">
  <POU Name="FB_TankController" Id="{c5e85192-36f8-483e-b1a4-1c5b3e658233}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION_BLOCK FB_TankController IMPLEMENTS I_TankController

VAR_IN_OUT
	nNum : INT;
END_VAR
VAR
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[]]></ST>
    </Implementation>
    <Method Name="ApplyCooling" Id="{426552bd-63fa-4d79-8c07-4fdfe2acc75d}">
      <Declaration><![CDATA[{warning 'add method implementation '}
METHOD ApplyCooling
]]></Declaration>
      <Implementation>
        <ST><![CDATA[]]></ST>
      </Implementation>
    </Method>
    <LineIds Name="FB_TankController">
      <LineId Id="9" Count="0" />
    </LineIds>
    <LineIds Name="FB_TankController.ApplyCooling">
      <LineId Id="4" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>