<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.16">
  <POU Name="FB_WareHouseController" Id="{f71319f3-9f03-4413-b277-c827ef65a8cb}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION_BLOCK FB_WareHouseController
VAR_INPUT
END_VAR
VAR_OUTPUT
END_VAR
VAR
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[]]></ST>
    </Implementation>
    <LineIds Name="FB_WareHouseController">
      <LineId Id="9" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>