<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.16">
  <POU Name="MAIN" Id="{35a7ba89-cc06-46c8-9519-2cb750099650}" SpecialFunc="None">
    <Declaration><![CDATA[PROGRAM MAIN
VAR
	
	fbConveyor : FB_Conveyor;
	iConveyor : I_Conveyor;
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[iConveyor := fbConveyor;
]]></ST>
    </Implementation>
    <LineIds Name="MAIN">
      <LineId Id="2" Count="0" />
      <LineId Id="9" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>